In [1]:
import torch

In [2]:
def print_tens_info(tensor):
    print("X :\n%s\n" % tensor)
    print("X количество измерений:\n%s\n" % tensor.dim())
    print("X размеры : ",  tensor.size())
    print("X тип : %s\n" % (tensor.type()))

In [3]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.rand(3, 4, 5)
print_tens_info(x)

X :
tensor([[[0.3036, 0.2947, 0.4591, 0.4405, 0.4538],
         [0.8216, 0.1577, 0.2098, 0.4180, 0.3976],
         [0.1014, 0.2534, 0.3700, 0.6927, 0.2444],
         [0.4455, 0.4522, 0.6922, 0.7391, 0.9676]],

        [[0.1533, 0.5271, 0.1999, 0.6976, 0.0489],
         [0.3575, 0.7032, 0.4397, 0.2696, 0.4541],
         [0.0911, 0.4179, 0.5227, 0.4387, 0.2667],
         [0.3725, 0.1809, 0.6342, 0.4086, 0.2528]],

        [[0.5300, 0.4356, 0.7280, 0.6394, 0.9412],
         [0.6528, 0.8379, 0.4501, 0.1545, 0.7916],
         [0.4579, 0.2651, 0.2046, 0.8257, 0.8879],
         [0.7967, 0.8941, 0.4439, 0.6032, 0.7670]]])

X количество измерений:
3

X размеры :  torch.Size([3, 4, 5])
X тип : torch.FloatTensor



In [4]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [5]:
# Приведите его к форме 6 X 10
print_tens_info(x.view(6, 10))

X :
tensor([[0.3036, 0.2947, 0.4591, 0.4405, 0.4538, 0.8216, 0.1577, 0.2098, 0.4180,
         0.3976],
        [0.1014, 0.2534, 0.3700, 0.6927, 0.2444, 0.4455, 0.4522, 0.6922, 0.7391,
         0.9676],
        [0.1533, 0.5271, 0.1999, 0.6976, 0.0489, 0.3575, 0.7032, 0.4397, 0.2696,
         0.4541],
        [0.0911, 0.4179, 0.5227, 0.4387, 0.2667, 0.3725, 0.1809, 0.6342, 0.4086,
         0.2528],
        [0.5300, 0.4356, 0.7280, 0.6394, 0.9412, 0.6528, 0.8379, 0.4501, 0.1545,
         0.7916],
        [0.4579, 0.2651, 0.2046, 0.8257, 0.8879, 0.7967, 0.8941, 0.4439, 0.6032,
         0.7670]])

X количество измерений:
2

X размеры :  torch.Size([6, 10])
X тип : torch.FloatTensor



In [6]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

# Размер тензора должен иметь значение = 5 в последнем измерении
# Умножаем исходный тензор размера 3x4x5 на вектор
vector = torch.LongTensor([1, 4, 2, 2, 1])
print_tens_info(x * vector)

X :
tensor([[[0.3036, 1.1788, 0.9182, 0.8811, 0.4538],
         [0.8216, 0.6307, 0.4196, 0.8360, 0.3976],
         [0.1014, 1.0136, 0.7399, 1.3853, 0.2444],
         [0.4455, 1.8089, 1.3845, 1.4782, 0.9676]],

        [[0.1533, 2.1086, 0.3998, 1.3951, 0.0489],
         [0.3575, 2.8128, 0.8795, 0.5391, 0.4541],
         [0.0911, 1.6717, 1.0455, 0.8774, 0.2667],
         [0.3725, 0.7236, 1.2684, 0.8172, 0.2528]],

        [[0.5300, 1.7423, 1.4561, 1.2788, 0.9412],
         [0.6528, 3.3515, 0.9001, 0.3089, 0.7916],
         [0.4579, 1.0603, 0.4093, 1.6513, 0.8879],
         [0.7967, 3.5764, 0.8877, 1.2065, 0.7670]]])

X количество измерений:
3

X размеры :  torch.Size([3, 4, 5])
X тип : torch.FloatTensor



In [7]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
print_tens_info(torch.matmul(x.view(6,10), x.view(6,10).t()))

X :
tensor([[1.8665, 1.9676, 1.4133, 1.4441, 2.4745, 2.5235],
        [1.9676, 3.1156, 2.1386, 1.9110, 2.9677, 3.2328],
        [1.4133, 2.1386, 1.9249, 1.4221, 2.3700, 2.4899],
        [1.4441, 1.9110, 1.4221, 1.5244, 2.0858, 2.0389],
        [2.4745, 2.9677, 2.3700, 2.0858, 4.2765, 4.0401],
        [2.5235, 3.2328, 2.4899, 2.0389, 4.0401, 4.3753]])

X количество измерений:
2

X размеры :  torch.Size([6, 6])
X тип : torch.FloatTensor



In [8]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [9]:
from torch.autograd import Variable

In [10]:
x = Variable(torch.ones(3), requires_grad = True)
z = Variable(torch.ones(3), requires_grad = True)
t = Variable(torch.ones(3), requires_grad = True)

y = x**3 + z - 75*t

x_0 = torch.FloatTensor([1, 0.5, 2])

In [11]:
print_tens_info(y)

X :
tensor([-73., -73., -73.], grad_fn=<SubBackward0>)

X количество измерений:
1

X размеры :  torch.Size([3])
X тип : torch.FloatTensor



In [12]:
print(x.grad)

None


In [13]:
y.backward(x_0)

In [14]:
print(x.grad)
print(z.grad)
print(t.grad)

tensor([3.0000, 1.5000, 6.0000])
tensor([1.0000, 0.5000, 2.0000])
tensor([ -75.0000,  -37.5000, -150.0000])


In [15]:
# Создайте единичный тензор размера 5x6
x = torch.eye(5, 6)
print_tens_info(x)

X :
tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])

X количество измерений:
2

X размеры :  torch.Size([5, 6])
X тип : torch.FloatTensor



In [16]:
# Переведите его в формат numpy
x = x.numpy()
x

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)

In [17]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

Похоже что задание до конца не сформулировано.